### ISSUE TITLE
Test in IE

### ISSUE THREAD

**Issue by Bekt** [Bekt/invatar#1]
I don't have access to Windows, so if somebody could take a screenshot of the readme from IE, that would be great.

**Comment by dor-rondel** [comment]
## **Edge:**

  ![edge](https://cloud.githubusercontent.com/assets/12615947/10236568/1e32a9f0-6875-11e5-8925-9a68d5f57166.jpg)

## **IE 11:** 

![explorer](https://cloud.githubusercontent.com/assets/12615947/10236574/3084898e-6875-11e5-8904-cb30a824e375.jpg)

p.s. Thanks for the new gravatar :+1:

**Comment by Bekt** [comment]
Avatar looks good @Dor-Ron :)

The website is empty right now, could you take a screenshot of the "demo" section of the Readme instead? https://github.com/Bekt/invatar/blob/master/README.md

**Comment by dor-rondel** [comment]
My bad, misunderstanding on my part. Here you go:

# **Edge:**

![screenshot 5](https://cloud.githubusercontent.com/assets/12615947/10238614/104ce394-6890-11e5-9bb0-0315930323f2.png)

![screenshot 6](https://cloud.githubusercontent.com/assets/12615947/10238616/1498cea4-6890-11e5-9e5a-cb199af27f86.png)

![screenshot 7](https://cloud.githubusercontent.com/assets/12615947/10238617/1793000c-6890-11e5-81d5-093d2841bd96.png)

# **IE 11:**

![screenshot 8](https://cloud.githubusercontent.com/assets/12615947/10238622/269e3f08-6890-11e5-8a3f-7001bfefea90.png)

![screenshot 9](https://cloud.githubusercontent.com/assets/12615947/10238624/2e02c020-6890-11e5-8158-7425e25ddde4.png)

![screenshot 10](https://cloud.githubusercontent.com/assets/12615947/10238626/317a2bb2-6890-11e5-8b95-e6ecea7e7d10.png)

**Comment by Bekt** [comment]
Nice thanks.

Haha well typical IE...

**Comment by dor-rondel** [comment]
No problem :)
That is why as you can see chrome is open right next to it haha

**Comment by Bekt** [comment]
Opened #3.
