### ISSUE TITLE
Error 0004. Unable to load the image.

### ISSUE THREAD

**Issue by mayorbrain** [Bekt/invatar#12]
I get the above error when I use invatar as a fallback for gravatar.

https://www.gravatar.com/avatar/0687fc8755ee10a335f8c1b514e39f18?d=https%3A%2F%2Finvatar0.appspot.com%2Fsvg%2FAS.jpg%3Fs%3D150

**Comment by Bekt** [comment]
Oh that's nasty.

From this page https://blog.gravatar.com/2012/10/09/default-image-changes/:

> If your default image is not publicly accessible, doesn’t have a file extension, **is not actually an image**, ... it cannot be used as the fallback/default image for a Gravatar. On the backend, we are now processing default images through a new service we have been working on called Photon

I'm not sure what kind of checks Photon does, but it looks like it doesn't recognize SVG's as valid image. Invatar returns an SVG image, not a regular image.

**Comment by mayorbrain** [comment]
I understand. That would mean invatar may not be functional as a fallback for gravatar.
