### ISSUE TITLE
Add cyrillic support

### ISSUE THREAD

**Issue by jungornti** [Bekt/invatar#7]
Hello, there are error 500 happened when i tried to use cyrillic letters:

for example:
https://invatar0.appspot.com/svg/%D0%BB%D1%81.jpg
https://invatar0.appspot.com/svg/фп.jpg

**Comment by Bekt** [comment]
Ahh, infamous Python(2) unicode hell. I'll look into this later today.

Also, I'm just going to trust python's [`.upper()`](https://docs.python.org/2/library/stdtypes.html#str.upper) method with uppercasing unicode (including cyrillic) letters.

**Comment by jungornti** [comment]
Sure, i can help with testing (only from monday till friday).

**Comment by jungornti** [comment]
Great. Thank you.
